[
   Schema                                               -- _1 _2 KW["{"] _3 _4 _5 KW["}"],
   Schema.1:ci-lit                                      -- _1,
   Schema.1:ci-lit.1:"schema"                           -- ,
   Schema.3:iter-star-sep                               -- _1 KW[","],
   Schema.4:iter-star-sep                               -- _1 KW[","],
   Schema.5:iter-star-sep                               -- _1 KW[","],
   Table                                                -- _1 _2 KW["{"] _3 KW["}"],
   Table.1:ci-lit                                       -- _1,
   Table.1:ci-lit.1:"table"                             -- ,
   Table.3:iter-star-sep                                -- _1 KW[","],
   Column                                               -- _1 _2 _3 _4 _5 _6 _7 _8,
   Column.1:ci-lit                                      -- _1,
   Column.1:ci-lit.1:"column"                           -- ,
   Column.8:opt                                         -- _1,
   Varchar                                              -- _1 _2 _3 _4,
   Varchar.1:ci-lit                                     -- _1,
   Varchar.1:ci-lit.1:"varchar"                         -- ,
   Varchar.2:ci-lit                                     -- _1,
   Varchar.2:ci-lit.1:"("                               -- ,
   Varchar.4:ci-lit                                     -- _1,
   Varchar.4:ci-lit.1:")"                               -- ,
   Int                                                  -- _1,
   Int.1:ci-lit                                         -- _1,
   Int.1:ci-lit.1:"INT"                                 -- ,
   Bit                                                  -- _1,
   Bit.1:ci-lit                                         -- _1,
   Bit.1:ci-lit.1:"bit"                                 -- ,
   Datetime                                             -- _1,
   Datetime.1:ci-lit                                    -- _1,
   Datetime.1:ci-lit.1:"datetime"                       -- ,
   True                                                 -- _1,
   True.1:ci-lit                                        -- _1,
   True.1:ci-lit.1:"true"                               -- ,
   False                                                -- _1,
   False.1:ci-lit                                       -- _1,
   False.1:ci-lit.1:"false"                             -- ,
   AutoIncrement                                        -- _1,
   AutoIncrement.1:ci-lit                               -- _1,
   AutoIncrement.1:ci-lit.1:"auto_increment"            -- ,
   NoExtra                                              -- _1,
   NoExtra.1:ci-lit                                     -- _1,
   NoExtra.1:ci-lit.1:"/\"/\""                          -- ,
   Primary                                              -- _1,
   Primary.1:ci-lit                                     -- _1,
   Primary.1:ci-lit.1:"Primary"                         -- ,
   Unique                                               -- _1,
   Unique.1:ci-lit                                      -- _1,
   Unique.1:ci-lit.1:"Unique"                           -- ,
   Multiple                                             -- _1,
   Multiple.1:ci-lit                                    -- _1,
   Multiple.1:ci-lit.1:"Multiple"                       -- ,
   NoKey                                                -- _1,
   NoKey.1:ci-lit                                       -- _1,
   NoKey.1:ci-lit.1:"None"                              -- ,
   Reference                                            -- _1 _2 _3 _4 _5,
   Reference.1:ci-lit                                   -- _1,
   Reference.1:ci-lit.1:"References"                    -- ,
   Reference.3:ci-lit                                   -- _1,
   Reference.3:ci-lit.1:"("                             -- ,
   Reference.4:iter-star-sep                            -- _1 KW[","],
   Reference.5:ci-lit                                   -- _1,
   Reference.5:ci-lit.1:")"                             -- ,
   StatementList                                        -- KW["("] _1 KW[")"],
   StatementList.1:iter-star-sep                        -- _1 KW[";"],
   Procedure                                            -- _1 _2 KW["("] _3 KW[")"] _4 _5,
   Procedure.1:ci-lit                                   -- _1,
   Procedure.1:ci-lit.1:"procedure"                     -- ,
   Procedure.3:iter-star-sep                            -- _1 KW[","],
   Input                                                -- _1 _2 _3,
   Input.1:ci-lit                                       -- _1,
   Input.1:ci-lit.1:"in"                                -- ,
   Output                                               -- _1 _2 _3,
   Output.1:ci-lit                                      -- _1,
   Output.1:ci-lit.1:"out"                              -- ,
   InOut                                                -- _1 _2 _3,
   InOut.1:ci-lit                                       -- _1,
   InOut.1:ci-lit.1:"inout"                             -- ,
   IfThen                                               -- _1 _2 _3 _4 _5 _6 _7,
   IfThen.1:ci-lit                                      -- _1,
   IfThen.1:ci-lit.1:"if"                               -- ,
   IfThen.3:ci-lit                                      -- _1,
   IfThen.3:ci-lit.1:"then"                             -- ,
   IfThen.5:iter-star-sep                               -- _1 KW[";"],
   IfThen.6:opt                                         -- _1,
   IfThen.7:ci-lit                                      -- _1,
   IfThen.7:ci-lit.1:"end if"                           -- ,
   BeginEnd                                             -- _1 _2 _3 _4,
   BeginEnd.1:ci-lit                                    -- _1,
   BeginEnd.1:ci-lit.1:"begin"                          -- ,
   BeginEnd.4:ci-lit                                    -- _1,
   BeginEnd.4:ci-lit.1:"end"                            -- ,
   Insert                                               -- _1,
   Delete                                               -- _1,
   Delete.1:ci-lit                                      -- _1,
   Delete.1:ci-lit.1:"delete"                           -- ,
   Star                                                 -- _1,
   Star.1:ci-lit                                        -- _1,
   Star.1:ci-lit.1:"*"                                  -- ,
   True                                                 -- _1,
   True.1:ci-lit                                        -- _1,
   True.1:ci-lit.1:"true"                               -- ,
   False                                                -- _1,
   False.1:ci-lit                                       -- _1,
   False.1:ci-lit.1:"false"                             -- ,
   ElseIf                                               -- _1 _2 _3 _4,
   ElseIf.1:ci-lit                                      -- _1,
   ElseIf.1:ci-lit.1:"elseif"                           -- ,
   ElseIf.3:ci-lit                                      -- _1,
   ElseIf.3:ci-lit.1:"then"                             -- ,
   Else                                                 -- _1 _2,
   Else.1:ci-lit                                        -- _1,
   Else.1:ci-lit.1:"else"                               -- ,
   Or                                                   -- _1 KW["OR"] _2,
   Or                                                   -- _1 KW["||"] _2,
   Xor                                                  -- _1 KW["XOR"] _2,
   And                                                  -- _1 KW["AND"] _2,
   And                                                  -- _1 KW["&&"] _2,
   Not                                                  -- KW["NOT"] _1,
   Not                                                  -- KW["!"] _1,
   Is                                                   -- _1 KW["IS"] _2 _3,
   Is.2:opt                                             -- _1,
   True                                                 -- KW["True"],
   False                                                -- KW["False"],
   Unknown                                              -- KW["Unknown"],
   Not                                                  -- KW["Not"],
   IsNull                                               -- _1 KW["IS"] _2 KW["NULL"],
   IsNull.2:opt                                         -- _1,
   Iff                                                  -- _1 KW["<=>"] _2,
   Equal                                                -- _1 KW["="] _2,
   GreaterThanEqual                                     -- _1 KW[">="] _2,
   GreaterThan                                          -- _1 KW[">"] _2,
   LessThanEqual                                        -- _1 KW["<="] _2,
   LessThan                                             -- _1 KW["<"] _2,
   NotEqual                                             -- _1 KW["<>"] _2,
   NotEqual                                             -- _1 KW["!="] _2,
   Equal                                                -- _1 KW["="] _2 _3,
   GreaterThanEqual                                     -- _1 KW[">="] _2 _3,
   GreaterThan                                          -- _1 KW[">"] _2 _3,
   LessThanEqual                                        -- _1 KW["<="] _2 _3,
   LessThan                                             -- _1 KW["<"] _2 _3,
   NotEqual                                             -- _1 KW["<>"] _2 _3,
   NotEqual                                             -- _1 KW["!="] _2 _3,
   All                                                  -- KW["ALL"],
   All                                                  -- KW["ANY"],
   InQuery                                              -- _1 _2 KW["IN"] _3,
   InQuery.2:opt                                        -- _1,
   InSet                                                -- _1 _2 KW["IN"] _3,
   InSet.2:opt                                          -- _1,
   Between                                              -- _1 _2 KW["BETWEEN"] _3 KW["AND"] _4,
   Between.2:opt                                        -- _1,
   SoundsLike                                           -- _1 KW["SOUNDS LIKE"] _2,
   Like                                                 -- _1 _2 KW["LIKE"] _3 _4,
   Like.2:opt                                           -- _1,
   Like.4:opt                                           -- _1,
   Regexp                                               -- _1 _2 KW["REGEXP"] _3,
   Regexp.2:opt                                         -- _1,
   Escape                                               -- KW["ESCAPE"] _1,
   BitOr                                                -- _1 KW["|"] _2,
   BitAnd                                               -- _1 KW["&"] _2,
   BitShiftLeft                                         -- _1 KW["<<"] _2,
   BitShiftRight                                        -- _1 KW[">>"] _2,
   Plus                                                 -- _1 KW["+"] _2,
   Minus                                                -- _1 KW["-"] _2,
   Multiply                                             -- _1 KW["*"] _2,
   Divide                                               -- _1 KW["/"] _2,
   Div                                                  -- _1 KW["DIV"] _2,
   Mod                                                  -- _1 KW["MOD"] _2,
   Percent                                              -- _1 KW["%"] _2,
   Power                                                -- _1 KW["^"] _2,
   PlusInt                                              -- _1 KW["+"] _2,
   MinusInt                                             -- _1 KW["-"] _2,
   Collate                                              -- _1 KW["COLLATE"] _2,
   Or                                                   -- _1 KW["||"] _2,
   UnaryPlus                                            -- KW["+"] _1,
   UnaryMinus                                           -- KW["-"] _1,
   Reverse                                              -- KW["~"] _1,
   Not                                                  -- KW["!"] _1,
   Binary                                               -- KW["BINARY"] _1,
   SetExpression                                        -- _1 _2 _3,
   SetExpression.1:ci-lit                               -- _1,
   SetExpression.1:ci-lit.1:"("                         -- ,
   SetExpression.2:iter-sep                             -- _1 KW[","],
   SetExpression.3:ci-lit                               -- _1,
   SetExpression.3:ci-lit.1:")"                         -- ,
   Row                                                  -- KW["ROW"] _1 KW[","] _2,
   Row.2:iter-sep                                       -- _1 KW[","],
   Exists                                               -- KW["EXISTS"] _1,
   EscapeSyntax                                         -- _1 _2 _3 _4,
   EscapeSyntax.1:ci-lit                                -- _1,
   EscapeSyntax.1:ci-lit.1:"{"                          -- ,
   EscapeSyntax.4:ci-lit                                -- _1,
   EscapeSyntax.4:ci-lit.1:"}"                          -- ,
   String                                               -- _1,
   Int                                                  -- _1,
   True                                                 -- _1,
   True.1:ci-lit                                        -- _1,
   True.1:ci-lit.1:"true"                               -- ,
   False                                                -- _1,
   False.1:ci-lit                                       -- _1,
   False.1:ci-lit.1:"false"                             -- ,
   Null                                                 -- _1,
   Null.1:ci-lit                                        -- _1,
   Null.1:ci-lit.1:"null"                               -- ,
   ColumnName                                           -- _1,
   TableColumnName                                      -- _1 _2 _3,
   TableColumnName.2:ci-lit                             -- _1,
   TableColumnName.2:ci-lit.1:"."                       -- ,
   DBTableColumnName                                    -- _1 _2 _3 _4 _5,
   DBTableColumnName.2:ci-lit                           -- _1,
   DBTableColumnName.2:ci-lit.1:"."                     -- ,
   DBTableColumnName.4:ci-lit                           -- _1,
   DBTableColumnName.4:ci-lit.1:"."                     -- ,
   LocalVariable                                        -- _1 _2,
   LocalVariable.1:ci-lit                               -- _1,
   LocalVariable.1:ci-lit.1:"@"                         -- ,
   SystemVariable                                       -- _1,
   Marker                                               -- _1,
   Marker.1:ci-lit                                      -- _1,
   Marker.1:ci-lit.1:"?"                                -- ,
   MatchExpression                                      -- KW["MATCH"] _1 _2 _3 KW["AGAINST"] _4 _5 _6 _7,
   MatchExpression.1:ci-lit                             -- _1,
   MatchExpression.1:ci-lit.1:"("                       -- ,
   MatchExpression.2:iter-sep                           -- _1 KW[","],
   MatchExpression.3:ci-lit                             -- _1,
   MatchExpression.3:ci-lit.1:")"                       -- ,
   MatchExpression.4:ci-lit                             -- _1,
   MatchExpression.4:ci-lit.1:"("                       -- ,
   MatchExpression.6:opt                                -- _1,
   MatchExpression.7:ci-lit                             -- _1,
   MatchExpression.7:ci-lit.1:")"                       -- ,
   InBooleanMode                                        -- KW["IN BOOLEAN MODE"],
   WithQueryExpansion                                   -- KW["WITH QUERY EXPANSION"],
   IntervalExpression                                   -- KW["INTERVAL"] _1 _2,
   MicroSecondUnit                                      -- KW["MICROSECOND"],
   SecondUnit                                           -- KW["SECOND"],
   MinuteUnit                                           -- KW["MINUTE"],
   HourUnit                                             -- KW["HOUR"],
   DayUnit                                              -- KW["DAY"],
   WeekUnit                                             -- KW["WEEK"],
   MonthUnit                                            -- KW["MONTH"],
   QuarterUnit                                          -- KW["QUARTER"],
   YearUnit                                             -- KW["YEAR"],
   SecondMicroSecondUnit                                -- KW["SECOND_MICROSECOND"],
   MinuteMicroSecondUnit                                -- KW["MINUTE_MICROSECOND"],
   MinuteSecondUnit                                     -- KW["MINUTE_SECOND"],
   HourMicroSecondUnit                                  -- KW["HOUR_MICROSECOND"],
   HourSecondUnit                                       -- KW["HOUR_SECOND"],
   HourMinuteUnit                                       -- KW["HOUR_MINUTE"],
   DayMicroSecondUnit                                   -- KW["DAY_MICROSECOND"],
   DaySecondUnit                                        -- KW["DAY_SECOND"],
   DayMinuteUnit                                        -- KW["DAY_MINUTE"],
   DayHourUnit                                          -- KW["DAY_HOUR"],
   YearMonthUnit                                        -- KW["YEAR_MONTH"],
   CaseExpression                                       -- KW["CASE"] _1 _2 _3 KW["END"],
   CaseExpression.2:iter-sep                            -- _1 KW[""],
   CaseExpression.3:opt                                 -- _1,
   CaseWhen                                             -- KW["WHEN"] _1 KW["THEN"] _2,
   CaseElse                                             -- KW["ELSE"] _1,
   FunctionCall                                         -- _1 _2 _3 _4,
   FunctionCall.2:ci-lit                                -- _1,
   FunctionCall.2:ci-lit.1:"("                          -- ,
   FunctionCall.3:iter-star-sep                         -- _1 KW[","],
   FunctionCall.4:ci-lit                                -- _1,
   FunctionCall.4:ci-lit.1:")"                          -- ,
   Select                                               -- KW["SELECT"] _1 _2 _3 _4 _5 _6 _7 _8 _9 _10 _11,
   Select.1:iter-star-sep                               -- _1 KW[""],
   Select.2:iter-sep                                    -- _1 KW[","],
   Select.3:opt                                         -- _1,
   Select.4:opt                                         -- _1,
   Select.5:opt                                         -- _1,
   Select.6:opt                                         -- _1,
   Select.7:opt                                         -- _1,
   Select.8:opt                                         -- _1,
   Select.9:opt                                         -- _1,
   Select.10:opt                                        -- _1,
   Select.11:opt                                        -- _1,
   All                                                  -- KW["ALL"],
   Distinct                                             -- KW["DISTINCT"],
   DistinctRow                                          -- KW["DISTINCTROW"],
   HighPriority                                         -- KW["HIGH_PRIORITY"],
   StraightJoin                                         -- KW["STRAIGHT_JOIN"],
   SmallResult                                          -- KW["SQL_SMALL_RESULT"],
   BigResult                                            -- KW["SQL_BIG_RESULT"],
   BufferResult                                         -- KW["SQL_BUFFER_RESULT"],
   Cache                                                -- KW["SQL_CACHE"],
   NoCache                                              -- KW["SQL_NO_CACHE"],
   CalcFoundRows                                        -- KW["SQL_CALC_FOUND_ROWS"],
   ColumnName                                           -- _1,
   TableColumnName                                      -- _1 _2 _3,
   TableColumnName.2:ci-lit                             -- _1,
   TableColumnName.2:ci-lit.1:"."                       -- ,
   ExpressionAs                                         -- _1 _2 _3,
   ExpressionAs.2:ci-lit                                -- _1,
   ExpressionAs.2:ci-lit.1:"AS"                         -- ,
   ColumnNameAs                                         -- _1 _2 _3,
   ColumnNameAs.2:ci-lit                                -- _1,
   ColumnNameAs.2:ci-lit.1:"AS"                         -- ,
   TableColumnNameAs                                    -- _1 _2 _3 _4 _5,
   TableColumnNameAs.2:ci-lit                           -- _1,
   TableColumnNameAs.2:ci-lit.1:"."                     -- ,
   TableColumnNameAs.4:ci-lit                           -- _1,
   TableColumnNameAs.4:ci-lit.1:"AS"                    -- ,
   Star                                                 -- _1,
   Star.1:ci-lit                                        -- _1,
   Star.1:ci-lit.1:"*"                                  -- ,
   FromPart                                             -- V  [H  [KW["FROM"]] _1],
   FromPart.1:iter-star-sep                             -- _1 KW[""],
   Where                                                -- KW["WHERE"] _1,
   GroupByPart                                          -- KW["GROUP BY"] _1 _2 _3,
   GroupByPart.2:opt                                    -- _1,
   GroupByPart.3:opt                                    -- _1,
   Rollup                                               -- KW["WITH ROLLUP"],
   Ascending                                            -- KW["ASC"],
   Descending                                           -- KW["DESC"],
   HavingPart                                           -- KW["HAVING"] _1,
   OrderByPart                                          -- KW["ORDER BY"] _1 _2,
   OrderByPart.2:opt                                    -- _1,
   LimitOffset                                          -- KW["LIMIT"] _1 _2,
   LimitOffset.1:opt                                    -- _1,
   LimitOffset                                          -- KW["LIMIT"] _1 KW["OFFSET"] _2,
   ProcedurePart                                        -- KW["PROCEDURE"] _1 _2 _3 _4,
   ProcedurePart.2:ci-lit                               -- _1,
   ProcedurePart.2:ci-lit.1:"("                         -- ,
   ProcedurePart.3:iter-star-sep                        -- _1 KW[","],
   ProcedurePart.4:ci-lit                               -- _1,
   ProcedurePart.4:ci-lit.1:")"                         -- ,
   IntoOutFile                                          -- KW["INTO OUTFILE"] _1 _2 _3,
   IntoOutFile.2:opt                                    -- _1,
   IntoDumpFile                                         -- KW["INTO DUMPFILE"] _1,
   Into                                                 -- V  [H  [KW["INTO"]] _1],
   Into.1:iter-star-sep                                 -- _1 KW[","],
   CharSet                                              -- KW["CHARACTER SET"] _1,
   ForUpdate                                            -- KW["FOR UPDATE"],
   LockShareMode                                        -- KW["LOCK IN SHARE MODE"],
   ExportOptions                                        -- KW["ExportOptionsUnknown"],
   TableName                                            -- _1,
   Aliased                                              -- _1 _2 _3,
   Aliased.3:iter-star-sep                              -- _1 KW[""],
   Query                                                -- _1 _2,
   Bracket                                              -- _1 _2 _3,
   Bracket.1:ci-lit                                     -- _1,
   Bracket.1:ci-lit.1:"("                               -- ,
   Bracket.2:iter-star-sep                              -- _1 KW[""],
   Bracket.3:ci-lit                                     -- _1,
   Bracket.3:ci-lit.1:")"                               -- ,
   OJ                                                   -- KW["OJ"] _1 _2 _3 KW["ON"] _4,
   OJ.2:ci-lit                                          -- _1,
   OJ.2:ci-lit.1:"LEFT OUTER JOIN"                      -- ,
   Alias                                                -- KW["AS"] _1,
   InnerJoin                                            -- _1 KW["INNER JOIN"] _2 _3,
   InnerJoin.3:opt                                      -- _1,
   CrossJoin                                            -- _1 KW["CROSS JOIN"] _2 _3,
   CrossJoin.3:opt                                      -- _1,
   StraightJoin                                         -- _1 KW["STRAIGHT_JOIN"] _2 _3,
   StraightJoin.3:opt                                   -- _1,
   LeftJoin                                             -- _1 KW["LEFT JOIN"] _2 _3,
   LeftOuterJoin                                        -- _1 KW["LEFT OUTER JOIN"] _2 _3,
   RightJoin                                            -- _1 KW["RIGHT JOIN"] _2 _3,
   RightOuterJoin                                       -- _1 KW["RIGHT OUTER JOIN"] _2 _3,
   NaturalLeftJoin                                      -- _1 KW["NATURAL LEFT JOIN"] _2 _3,
   NaturalLeftOuterJoin                                 -- _1 KW["NATURAL LEFT OUTER JOIN"] _2 _3,
   NaturalRightJoin                                     -- _1 KW["NATURAL RIGHT JOIN"] _2 _3,
   NaturalRightOuterJoin                                -- _1 KW["NATURAL RIGHT OUTER JOIN"] _2 _3,
   On                                                   -- KW["ON"] _1,
   Using                                                -- V  [H  [KW["USING"]] _1],
   Using.1:iter-sep                                     -- _1 KW[","],
   Use                                                  -- KW["USE"] _1 _2,
   Use.2:opt                                            -- _1,
   Ignore                                               -- KW["IGNORE"] _1 _2,
   Ignore.2:opt                                         -- _1,
   Force                                                -- KW["FORCE"] _1 _2,
   Force.2:opt                                          -- _1,
   Index                                                -- KW["INDEX"],
   Key                                                  -- KW["KEY"],
   ForClause                                            -- KW["FOR"] _1 _2,
   ForClause.2:iter-sep                                 -- _1 KW[","],
   Join                                                 -- KW["JOIN"],
   OrderBy                                              -- KW["ORDER BY"],
   GroupBy                                              -- KW["GROUP BY"],
   Update                                               -- KW["UPDATE"] _1 _2 KW["SET"] _3 _4 _5 _6,
   Update.1:iter-star                                   -- _1,
   Update.3:iter                                        -- _1,
   Update.4:opt                                         -- _1,
   Update.5:opt                                         -- _1,
   Update.6:opt                                         -- _1,
   LowPriority                                          -- KW["LOW_PRIORITY"],
   Ignore                                               -- KW["IGNORE"],
   UpdateSet                                            -- _1 KW["="] _2,
   UpdateSetDefault                                     -- _1 KW["="] KW["DEFAULT"],
   Insert                                               -- _1 _2 _3 _4 _5 _6 _7 _8 _9 _10 _11 _12 _13,
   Insert.1:ci-lit                                      -- _1,
   Insert.1:ci-lit.1:"INSERT"                           -- ,
   Insert.2:opt                                         -- _1,
   Insert.3:opt                                         -- _1,
   Insert.4:opt                                         -- _1,
   Insert.6:ci-lit                                      -- _1,
   Insert.6:ci-lit.1:"("                                -- ,
   Insert.7:iter-star-sep                               -- _1 KW[","],
   Insert.8:ci-lit                                      -- _1,
   Insert.8:ci-lit.1:")"                                -- ,
   Insert.9:ci-lit                                      -- _1,
   Insert.9:ci-lit.1:"values"                           -- ,
   Insert.10:ci-lit                                     -- _1,
   Insert.10:ci-lit.1:"("                               -- ,
   Insert.11:iter-star-sep                              -- _1 KW[","],
   Insert.12:ci-lit                                     -- _1,
   Insert.12:ci-lit.1:")"                               -- ,
   Insert.13:opt                                        -- _1,
   LowPriority                                          -- _1,
   LowPriority.1:ci-lit                                 -- _1,
   LowPriority.1:ci-lit.1:"LOW_PRIORITY"                -- ,
   DelayedPriority                                      -- _1,
   DelayedPriority.1:ci-lit                             -- _1,
   DelayedPriority.1:ci-lit.1:"DELAYED"                 -- ,
   HighPriority                                         -- _1,
   HighPriority.1:ci-lit                                -- _1,
   HighPriority.1:ci-lit.1:"HIGH_PRIORITY"              -- ,
   Ignore                                               -- _1,
   Ignore.1:ci-lit                                      -- _1,
   Ignore.1:ci-lit.1:"IGNORE"                           -- ,
   Into                                                 -- _1,
   Into.1:ci-lit                                        -- _1,
   Into.1:ci-lit.1:"INTO"                               -- ,
   Values                                               -- _1,
   Values.1:ci-lit                                      -- _1,
   Values.1:ci-lit.1:"Values"                           -- ,
   Values                                               -- _1,
   Values.1:ci-lit                                      -- _1,
   Values.1:ci-lit.1:"Value"                            -- ,
   OnDuplicate                                          -- _1 _2 _3 _4 _5,
   OnDuplicate.1:ci-lit                                 -- _1,
   OnDuplicate.1:ci-lit.1:"ON"                          -- ,
   OnDuplicate.2:ci-lit                                 -- _1,
   OnDuplicate.2:ci-lit.1:"DUPLICATE"                   -- ,
   OnDuplicate.3:ci-lit                                 -- _1,
   OnDuplicate.3:ci-lit.1:"KEY"                         -- ,
   OnDuplicate.4:ci-lit                                 -- _1,
   OnDuplicate.4:ci-lit.1:"UPDATE"                      -- ,
   OnDuplicate.5:iter-star-sep                          -- _1 KW[","],
   UpdatePart                                           -- _1 _2 _3,
   UpdatePart.2:ci-lit                                  -- _1,
   UpdatePart.2:ci-lit.1:"="                            -- ,
   DeclareList                                          -- _1,
   DeclareList.1:iter-star-sep                          -- _1 KW[";"],
   Declare                                              -- _1 _2 _3 _4,
   Declare.1:ci-lit                                     -- _1,
   Declare.1:ci-lit.1:"DECLARE"                         -- ,
   Declare.2:iter-sep                                   -- _1 KW[","],
   Declare.4:opt                                        -- _1,
   DefaultDeclare                                       -- _1 _2,
   DefaultDeclare.1:ci-lit                              -- _1,
   DefaultDeclare.1:ci-lit.1:"default"                  -- ,
   MaxMult                                              -- _1,
   MaxMult                                              -- KW["*"],
   Ordering                                             -- KW["SET"],
   Ordering                                             -- KW["OSET"],
   Ordering                                             -- KW["SEQ"],
   Null                                                 -- _1,
   Null.1:ci-lit                                        -- _1,
   Null.1:ci-lit.1:"null"                               -- ,
   Int                                                  -- _1,
   Int.1:ci-lit                                         -- _1,
   Int.1:ci-lit.1:"INT"                                 -- ,
   String                                               -- _1,
   String.1:ci-lit                                      -- _1,
   String.1:ci-lit.1:"STRING"                           -- ,
   Class                                                -- _1,
   Optional                                             -- _1 _2 _3,
   Optional.1:ci-lit                                    -- _1,
   Optional.1:ci-lit.1:"["                              -- ,
   Optional.3:ci-lit                                    -- _1,
   Optional.3:ci-lit.1:"]"                              -- ,
   Set                                                  -- _1 _2 _3 _4,
   Set.1:ci-lit                                         -- _1,
   Set.1:ci-lit.1:"set"                                 -- ,
   Set.2:ci-lit                                         -- _1,
   Set.2:ci-lit.1:"("                                   -- ,
   Set.4:ci-lit                                         -- _1,
   Set.4:ci-lit.1:")"                                   -- ,
   Skip                                                 -- _1,
   Skip.1:ci-lit                                        -- _1,
   Skip.1:ci-lit.1:"skip"                               -- ,
   Assign                                               -- _1 _2 _3,
   Assign.2:ci-lit                                      -- _1,
   Assign.2:ci-lit.1:":="                               -- ,
   New                                                  -- _1 _2 _3 _4 _5,
   New.1:ci-lit                                         -- _1,
   New.1:ci-lit.1:"new"                                 -- ,
   New.3:ci-lit                                         -- _1,
   New.3:ci-lit.1:"!"                                   -- ,
   New.4:ci-lit                                         -- _1,
   New.4:ci-lit.1:":"                                   -- ,
   Guard                                                -- _1 _2 _3,
   Guard.2:ci-lit                                       -- _1,
   Guard.2:ci-lit.1:"-->"                               -- ,
   Parallel                                             -- _1 _2 _3,
   Parallel.2:ci-lit                                    -- _1,
   Parallel.2:ci-lit.1:"||"                             -- ,
   Sequence                                             -- _1 _2 _3,
   Sequence.2:ci-lit                                    -- _1,
   Sequence.2:ci-lit.1:";"                              -- ,
   Choice                                               -- _1 KW["["] KW["]"] _2,
   Any                                                  -- _1 _2 _3 _4 _5 _6,
   Any.1:ci-lit                                         -- _1,
   Any.1:ci-lit.1:"ALL"                                 -- ,
   Any.3:ci-lit                                         -- _1,
   Any.3:ci-lit.1:":"                                   -- ,
   Any.5:ci-lit                                         -- _1,
   Any.5:ci-lit.1:"."                                   -- ,
   All                                                  -- _1 _2 _3 _4 _5 _6,
   All.1:ci-lit                                         -- _1,
   All.1:ci-lit.1:"ANY"                                 -- ,
   All.3:ci-lit                                         -- _1,
   All.3:ci-lit.1:":"                                   -- ,
   All.5:ci-lit                                         -- _1,
   All.5:ci-lit.1:"."                                   -- ,
   System                                               -- _1 _2 _3,
   System.1:ci-lit                                      -- _1,
   System.1:ci-lit.1:"system"                           -- ,
   System.3:iter-star                                   -- _1,
   Class                                                -- _1 _2 _3 _4 _5 _6,
   Class.1:ci-lit                                       -- _1,
   Class.1:ci-lit.1:"class"                             -- ,
   Class.3:opt                                          -- _1,
   Class.4:ci-lit                                       -- _1,
   Class.4:ci-lit.1:"{"                                 -- ,
   Class.5:iter-star                                    -- _1,
   Class.6:ci-lit                                       -- _1,
   Class.6:ci-lit.1:"}"                                 -- ,
   Extend                                               -- _1 _2,
   Extend.1:ci-lit                                      -- _1,
   Extend.1:ci-lit.1:"extends"                          -- ,
   Extend.2:iter-sep                                    -- _1 _2,
   Extend.2:iter-sep.2:ci-lit                           -- _1,
   Extend.2:iter-sep.2:ci-lit.1:","                     -- ,
   Extension                                            -- _1,
   Attributes                                           -- _1 _2,
   Attributes.1:ci-lit                                  -- _1,
   Attributes.1:ci-lit.1:"attributes"                   -- ,
   Attributes.2:iter-star                               -- _1,
   Methods                                              -- _1 _2,
   Methods.1:ci-lit                                     -- _1,
   Methods.1:ci-lit.1:"methods"                         -- ,
   Methods.2:iter-star                                  -- _1,
   Invariant                                            -- _1 _2,
   Invariant.1:ci-lit                                   -- _1,
   Invariant.1:ci-lit.1:"invariants"                    -- ,
   Invariant.2:iter-star                                -- _1,
   SetDef                                               -- _1 _2 _3 _4 _5,
   SetDef.1:ci-lit                                      -- _1,
   SetDef.1:ci-lit.1:"set"                              -- ,
   SetDef.3:ci-lit                                      -- _1,
   SetDef.3:ci-lit.1:"{"                                -- ,
   SetDef.4:iter-sep                                    -- _1 _2,
   SetDef.4:iter-sep.2:ci-lit                           -- _1,
   SetDef.4:iter-sep.2:ci-lit.1:","                     -- ,
   SetDef.5:ci-lit                                      -- _1,
   SetDef.5:ci-lit.1:"}"                                -- ,
   Attribute                                            -- _1 _2 _3,
   Attribute.2:ci-lit                                   -- _1,
   Attribute.2:ci-lit.1:":"                             -- ,
   Attribute                                            -- _1 _2 _3 _4,
   Attribute.3:ci-lit                                   -- _1,
   Attribute.3:ci-lit.1:":"                             -- ,
   Attribute                                            -- _1 _2 _3,
   Attribute.2:ci-lit                                   -- _1,
   Attribute.2:ci-lit.1:":"                             -- ,
   Identity                                             -- _1 _2 _3,
   Identity.1:ci-lit                                    -- _1,
   Identity.1:ci-lit.1:"("                              -- ,
   Identity.2:ci-lit                                    -- _1,
   Identity.2:ci-lit.1:"ID"                             -- ,
   Identity.3:ci-lit                                    -- _1,
   Identity.3:ci-lit.1:")"                              -- ,
   Method                                               -- _1 _2 _3 _4,
   Method.2:ci-lit                                      -- _1,
   Method.2:ci-lit.1:"{"                                -- ,
   Method.4:ci-lit                                      -- _1,
   Method.4:ci-lit.1:"}"                                -- ,
   Method                                               -- _1 _2 _3 _4,
   Method.2:ci-lit                                      -- _1,
   Method.2:ci-lit.1:"{"                                -- ,
   Method.4:ci-lit                                      -- _1,
   Method.4:ci-lit.1:"}"                                -- ,
   Method                                               -- _1 _2 _3 _4,
   Method.2:ci-lit                                      -- _1,
   Method.2:ci-lit.1:"{"                                -- ,
   Method.4:ci-lit                                      -- _1,
   Method.4:ci-lit.1:"}"                                -- ,
   Optional                                             -- _1 _2 _3,
   Optional.1:ci-lit                                    -- _1,
   Optional.1:ci-lit.1:"["                              -- ,
   Optional.3:ci-lit                                    -- _1,
   Optional.3:ci-lit.1:"]"                              -- ,
   Set                                                  -- _1 _2 _3 _4 _5 _6 _7,
   Set.1:ci-lit                                         -- _1,
   Set.1:ci-lit.1:"set"                                 -- ,
   Set.2:ci-lit                                         -- _1,
   Set.2:ci-lit.1:"("                                   -- ,
   Set.4:ci-lit                                         -- _1,
   Set.4:ci-lit.1:")"                                   -- ,
   Set.5:ci-lit                                         -- _1,
   Set.5:ci-lit.1:"["                                   -- ,
   Set.7:ci-lit                                         -- _1,
   Set.7:ci-lit.1:"]"                                   -- ,
   BasicType                                            -- _1,
   String                                               -- _1,
   String.1:ci-lit                                      -- _1,
   String.1:ci-lit.1:"STRING"                           -- ,
   Int                                                  -- _1,
   Int.1:ci-lit                                         -- _1,
   Int.1:ci-lit.1:"INT"                                 -- ,
   DateTime                                             -- _1,
   DateTime.1:ci-lit                                    -- _1,
   DateTime.1:ci-lit.1:"DATETIME"                       -- ,
   Boolean                                              -- _1,
   Boolean.1:ci-lit                                     -- _1,
   Boolean.1:ci-lit.1:"BOOLEAN"                         -- ,
   UniDirectional                                       -- _1,
   BiDirectional                                        -- _1 _2 _3,
   BiDirectional.2:ci-lit                               -- _1,
   BiDirectional.2:ci-lit.1:"."                         -- ,
   MultMinAndMax                                        -- _1 _2 _3,
   MultMinAndMax.2:ci-lit                               -- _1,
   MultMinAndMax.2:ci-lit.1:".."                        -- ,
   MultJustMax                                          -- _1 _2,
   MultJustMax.1:ci-lit                                 -- _1,
   MultJustMax.1:ci-lit.1:".."                          -- ,
   MultJustMin                                          -- _1 _2,
   MultJustMin.2:ci-lit                                 -- _1,
   MultJustMin.2:ci-lit.1:".."                          -- ,
   MultJustMin                                          -- _1 _2 _3,
   MultJustMin.2:ci-lit                                 -- _1,
   MultJustMin.2:ci-lit.1:".."                          -- ,
   MultJustMin.3:ci-lit                                 -- _1,
   MultJustMin.3:ci-lit.1:"*"                           -- ,
   MultSingle                                           -- _1,
   MultAny                                              -- _1,
   MultAny.1:ci-lit                                     -- _1,
   MultAny.1:ci-lit.1:"*"                               -- ,
   True                                                 -- _1,
   True.1:ci-lit                                        -- _1,
   True.1:ci-lit.1:"true"                               -- ,
   False                                                -- _1,
   False.1:ci-lit                                       -- _1,
   False.1:ci-lit.1:"false"                             -- ,
   Not                                                  -- _1 _2,
   Not.1:ci-lit                                         -- _1,
   Not.1:ci-lit.1:"not"                                 -- ,
   And                                                  -- _1 _2 _3,
   And.2:ci-lit                                         -- _1,
   And.2:ci-lit.1:"&"                                   -- ,
   Or                                                   -- _1 _2 _3,
   Or.2:ci-lit                                          -- _1,
   Or.2:ci-lit.1:"or"                                   -- ,
   Implies                                              -- _1 _2 _3,
   Implies.2:ci-lit                                     -- _1,
   Implies.2:ci-lit.1:"=>"                              -- ,
   Then                                                 -- _1 _2 _3,
   Then.2:ci-lit                                        -- _1,
   Then.2:ci-lit.1:";"                                  -- ,
   MethodRef                                            -- _1,
   Exists                                               -- _1 _2 KW[":"] _3 KW["@"] _4,
   Exists.1:ci-lit                                      -- _1,
   Exists.1:ci-lit.1:"exists"                           -- ,
   Forall                                               -- _1 _2 KW[":"] _3 KW["@"] _4,
   Forall.1:ci-lit                                      -- _1,
   Forall.1:ci-lit.1:"forall"                           -- ,
   BinRel                                               -- _1 _2 _3,
   Equal                                                -- _1,
   Equal.1:ci-lit                                       -- _1,
   Equal.1:ci-lit.1:"="                                 -- ,
   NotEqual                                             -- _1,
   NotEqual.1:ci-lit                                    -- _1,
   NotEqual.1:ci-lit.1:"/="                             -- ,
   In                                                   -- _1,
   In.1:ci-lit                                          -- _1,
   In.1:ci-lit.1:":"                                    -- ,
   NotIn                                                -- _1,
   NotIn.1:ci-lit                                       -- _1,
   NotIn.1:ci-lit.1:"/:"                                -- ,
   LessThan                                             -- _1,
   LessThan.1:ci-lit                                    -- _1,
   LessThan.1:ci-lit.1:"<"                              -- ,
   GreaterThan                                          -- _1,
   GreaterThan.1:ci-lit                                 -- _1,
   GreaterThan.1:ci-lit.1:">"                           -- ,
   LessThanEquals                                       -- _1,
   LessThanEquals.1:ci-lit                              -- _1,
   LessThanEquals.1:ci-lit.1:"<="                       -- ,
   GreaterThanEquals                                    -- _1,
   GreaterThanEquals.1:ci-lit                           -- _1,
   GreaterThanEquals.1:ci-lit.1:">="                    -- ,
   Subset                                               -- _1,
   Subset.1:ci-lit                                      -- _1,
   Subset.1:ci-lit.1:"<:"                               -- ,
   SubsetEquals                                         -- _1,
   SubsetEquals.1:ci-lit                                -- _1,
   SubsetEquals.1:ci-lit.1:"<<:"                        -- ,
   Superset                                             -- _1,
   Superset.1:ci-lit                                    -- _1,
   Superset.1:ci-lit.1:":>"                             -- ,
   SupersetEquals                                       -- _1,
   SupersetEquals.1:ci-lit                              -- _1,
   SupersetEquals.1:ci-lit.1:":>>"                      -- ,
   BasicValue                                           -- _1,
   Integer                                              -- _1,
   String                                               -- _1,
   TypeExtent                                           -- _1,
   String                                               -- _1,
   String.1:ci-lit                                      -- _1,
   String.1:ci-lit.1:"string"                           -- ,
   Int                                                  -- _1,
   Int.1:ci-lit                                         -- _1,
   Int.1:ci-lit.1:"int"                                 -- ,
   DateTime                                             -- _1,
   DateTime.1:ci-lit                                    -- _1,
   DateTime.1:ci-lit.1:"datetime"                       -- ,
   Boolean                                              -- _1,
   Boolean.1:ci-lit                                     -- _1,
   Boolean.1:ci-lit.1:"boolean"                         -- ,
   Null                                                 -- _1,
   Null.1:ci-lit                                        -- _1,
   Null.1:ci-lit.1:"null"                               -- ,
   SetExtent                                            -- KW["{"] _1 KW["}"],
   SetExtent.1:iter-star-sep                            -- _1 KW[","],
   Head                                                 -- _1 _2,
   Head.1:ci-lit                                        -- _1,
   Head.1:ci-lit.1:"head"                               -- ,
   Tail                                                 -- _1 _2,
   Tail.1:ci-lit                                        -- _1,
   Tail.1:ci-lit.1:"tail"                               -- ,
   Cardinality                                          -- _1 _2,
   Cardinality.1:ci-lit                                 -- _1,
   Cardinality.1:ci-lit.1:"card"                        -- ,
   Negative                                             -- _1 _2,
   Negative.1:ci-lit                                    -- _1,
   Negative.1:ci-lit.1:"-"                              -- ,
   BinOp                                                -- _1 _2 _3,
   Plus                                                 -- KW["+"],
   Minus                                                -- KW["-"],
   Times                                                -- KW["*"],
   Divide                                               -- KW["/"],
   Maximum                                              -- KW["max"],
   Minimum                                              -- KW["min"],
   Intersection                                         -- KW["/\\"],
   Union                                                -- KW["\\/"],
   Concat                                               -- KW["++"],
   MethodReference                                      -- _1 _2 _3 _4,
   MethodReference.2:ci-lit                             -- _1,
   MethodReference.2:ci-lit.1:"("                       -- ,
   MethodReference.3:iter-star-sep                      -- _1 KW[","],
   MethodReference.3:iter-star-sep.1:seq                -- _1 _2 _3 _4,
   MethodReference.3:iter-star-sep.1:seq.2:ci-lit       -- _1,
   MethodReference.3:iter-star-sep.1:seq.2:ci-lit.1:"?" -- ,
   MethodReference.3:iter-star-sep.1:seq.3:ci-lit       -- _1,
   MethodReference.3:iter-star-sep.1:seq.3:ci-lit.1:"=" -- ,
   MethodReference.4:ci-lit                             -- _1,
   MethodReference.4:ci-lit.1:")"                       -- ,
   Path                                                 -- _1 _2 _3,
   Path.2:ci-lit                                        -- _1,
   Path.2:ci-lit.1:"."                                  -- ,
   PathStart                                            -- _1 _2,
   PathStart.2:opt                                      -- _1,
   Input                                                -- _1 KW["?"],
   Output                                               -- _1 KW["!"],
   This                                                 -- _1,
   This.1:ci-lit                                        -- _1,
   This.1:ci-lit.1:"this"                               -- ,
   ThisPrimed                                           -- _1 KW["'"],
   ThisPrimed.1:ci-lit                                  -- _1,
   ThisPrimed.1:ci-lit.1:"this"                         -- ,
   Primed                                               -- KW["'"],
   PathComponent                                        -- ,
   PathComponent                                        -- _1 _2,
   PathComponent.2:opt                                  -- _1
]