//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.24 at 09:10:54 AM BRT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.org/objectModel", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ox.softeng.gwi.ObjectModel;
