

set @output = 1;

CALL `Country_Create`('Afghanistan',@output);
CALL `Country_Create`('Albania',@output);
CALL `Country_Create`('Algeria',@output);
CALL `Country_Create`('American Samoa',@output);
CALL `Country_Create`('Andorra',@output);
CALL `Country_Create`('Angola',@output);
CALL `Country_Create`('Anguilla',@output);
CALL `Country_Create`('Antarctica',@output);
CALL `Country_Create`('Antigua And Barbuda',@output);
CALL `Country_Create`('Argentina',@output);
CALL `Country_Create`('Armenia',@output);
CALL `Country_Create`('Aruba',@output);
CALL `Country_Create`('Australia',@output);
CALL `Country_Create`('Austria',@output);
CALL `Country_Create`('Azerbaijan',@output);
CALL `Country_Create`('Bahamas',@output);
CALL `Country_Create`('Bahrain',@output);
CALL `Country_Create`('Bangladesh',@output);
CALL `Country_Create`('Barbados',@output);
CALL `Country_Create`('Belarus',@output);
CALL `Country_Create`('Belgium',@output);
CALL `Country_Create`('Belize',@output);
CALL `Country_Create`('Benin',@output);
CALL `Country_Create`('Bermuda',@output);
CALL `Country_Create`('Bhutan',@output);
CALL `Country_Create`('Bolivia',@output);
CALL `Country_Create`('Bosnia And Herzegovina',@output);
CALL `Country_Create`('Botswana',@output);
CALL `Country_Create`('Bouvet Island',@output);
CALL `Country_Create`('Brazil',@output);
CALL `Country_Create`('British Indian Ocean Territory',@output);
CALL `Country_Create`('Brunei Darussalam',@output);
CALL `Country_Create`('Bulgaria',@output);
CALL `Country_Create`('Burkina Faso',@output);
CALL `Country_Create`('Burundi',@output);
CALL `Country_Create`('Cambodia',@output);
CALL `Country_Create`('Cameroon',@output);
CALL `Country_Create`('Canada',@output);
CALL `Country_Create`('Cape Verde',@output);
CALL `Country_Create`('Cayman Islands',@output);
CALL `Country_Create`('Central African Republic',@output);
CALL `Country_Create`('Chad',@output);
CALL `Country_Create`('Chile',@output);
CALL `Country_Create`('China',@output);
CALL `Country_Create`('Christmas Island',@output);
CALL `Country_Create`('Cocos (Keeling) Islands',@output);
CALL `Country_Create`('Colombia',@output);
CALL `Country_Create`('Comoros',@output);
CALL `Country_Create`('Congo',@output);
CALL `Country_Create`('Congo, The Democratic Republic Of The',@output);
CALL `Country_Create`('Cook Islands',@output);
CALL `Country_Create`('Costa Rica',@output);
CALL `Country_Create`('Cote D''ivoire',@output);
CALL `Country_Create`('Croatia',@output);
CALL `Country_Create`('Cuba',@output);
CALL `Country_Create`('Cyprus',@output);
CALL `Country_Create`('Czech Republic',@output);
CALL `Country_Create`('Denmark',@output);
CALL `Country_Create`('Djibouti',@output);
CALL `Country_Create`('Dominica',@output);
CALL `Country_Create`('Dominican Republic',@output);
CALL `Country_Create`('Ecuador',@output);
CALL `Country_Create`('Egypt',@output);
CALL `Country_Create`('El Salvador',@output);
CALL `Country_Create`('Equatorial Guinea',@output);
CALL `Country_Create`('Eritrea',@output);
CALL `Country_Create`('Estonia',@output);
CALL `Country_Create`('Ethiopia',@output);
CALL `Country_Create`('Falkland Islands (Malvinas)',@output);
CALL `Country_Create`('Faroe Islands',@output);
CALL `Country_Create`('Fiji',@output);
CALL `Country_Create`('Finland',@output);
CALL `Country_Create`('France',@output);
CALL `Country_Create`('French Guiana',@output);
CALL `Country_Create`('French Polynesia',@output);
CALL `Country_Create`('French Southern Territories',@output);
CALL `Country_Create`('Gabon',@output);
CALL `Country_Create`('Gambia',@output);
CALL `Country_Create`('Georgia',@output);
CALL `Country_Create`('Germany',@output);
CALL `Country_Create`('Ghana',@output);
CALL `Country_Create`('Gibraltar',@output);
CALL `Country_Create`('Greece',@output);
CALL `Country_Create`('Greenland',@output);
CALL `Country_Create`('Grenada',@output);
CALL `Country_Create`('Guadeloupe',@output);
CALL `Country_Create`('Guam',@output);
CALL `Country_Create`('Guatemala',@output);
CALL `Country_Create`('Guernsey',@output);
CALL `Country_Create`('Guinea',@output);
CALL `Country_Create`('Guinea-bissau',@output);
CALL `Country_Create`('Guyana',@output);
CALL `Country_Create`('Haiti',@output);
CALL `Country_Create`('Heard Island And Mcdonald Islands',@output);
CALL `Country_Create`('Holy See (Vatican City State)',@output);
CALL `Country_Create`('Honduras',@output);
CALL `Country_Create`('Hong Kong',@output);
CALL `Country_Create`('Hungary',@output);
CALL `Country_Create`('Iceland',@output);
CALL `Country_Create`('India',@output);
CALL `Country_Create`('Indonesia',@output);
CALL `Country_Create`('Iran, Islamic Republic Of',@output);
CALL `Country_Create`('Iraq',@output);
CALL `Country_Create`('Ireland',@output);
CALL `Country_Create`('Isle Of Man',@output);
CALL `Country_Create`('Israel',@output);
CALL `Country_Create`('Italy',@output);
CALL `Country_Create`('Jamaica',@output);
CALL `Country_Create`('Japan',@output);
CALL `Country_Create`('Jersey',@output);
CALL `Country_Create`('Jordan',@output);
CALL `Country_Create`('Kazakhstan',@output);
CALL `Country_Create`('Kenya',@output);
CALL `Country_Create`('Kiribati',@output);
CALL `Country_Create`('Korea, Democratic People''s Republic Of',@output);
CALL `Country_Create`('Korea, Republic Of',@output);
CALL `Country_Create`('Kuwait',@output);
CALL `Country_Create`('Kyrgyzstan',@output);
CALL `Country_Create`('Lao People''s Democratic Republic',@output);
CALL `Country_Create`('Latvia',@output);
CALL `Country_Create`('Lebanon',@output);
CALL `Country_Create`('Lesotho',@output);
CALL `Country_Create`('Liberia',@output);
CALL `Country_Create`('Libyan Arab Jamahiriya',@output);
CALL `Country_Create`('Liechtenstein',@output);
CALL `Country_Create`('Lithuania',@output);
CALL `Country_Create`('Luxembourg',@output);
CALL `Country_Create`('Macao',@output);
CALL `Country_Create`('Macedonia, The Former Yugoslav Republic Of',@output);
CALL `Country_Create`('Madagascar',@output);
CALL `Country_Create`('Malawi',@output);
CALL `Country_Create`('Malaysia',@output);
CALL `Country_Create`('Maldives',@output);
CALL `Country_Create`('Mali',@output);
CALL `Country_Create`('Malta',@output);
CALL `Country_Create`('Marshall Islands',@output);
CALL `Country_Create`('Martinique',@output);
CALL `Country_Create`('Mauritania',@output);
CALL `Country_Create`('Mauritius',@output);
CALL `Country_Create`('Mayotte',@output);
CALL `Country_Create`('Mexico',@output);
CALL `Country_Create`('Micronesia, Federated States Of',@output);
CALL `Country_Create`('Moldova, Republic Of',@output);
CALL `Country_Create`('Monaco',@output);
CALL `Country_Create`('Mongolia',@output);
CALL `Country_Create`('Montenegro',@output);
CALL `Country_Create`('Montserrat',@output);
CALL `Country_Create`('Morocco',@output);
CALL `Country_Create`('Mozambique',@output);
CALL `Country_Create`('Myanmar',@output);
CALL `Country_Create`('Namibia',@output);
CALL `Country_Create`('Nauru',@output);
CALL `Country_Create`('Nepal',@output);
CALL `Country_Create`('Netherlands',@output);
CALL `Country_Create`('Netherlands Antilles',@output);
CALL `Country_Create`('New Caledonia',@output);
CALL `Country_Create`('New Zealand',@output);
CALL `Country_Create`('Nicaragua',@output);
CALL `Country_Create`('Niger',@output);
CALL `Country_Create`('Nigeria',@output);
CALL `Country_Create`('Niue',@output);
CALL `Country_Create`('Norfolk Island',@output);
CALL `Country_Create`('Northern Mariana Islands',@output);
CALL `Country_Create`('Norway',@output);
CALL `Country_Create`('Oman',@output);
CALL `Country_Create`('Pakistan',@output);
CALL `Country_Create`('Palau',@output);
CALL `Country_Create`('Palestinian Territory, Occupied',@output);
CALL `Country_Create`('Panama',@output);
CALL `Country_Create`('Papua New Guinea',@output);
CALL `Country_Create`('Paraguay',@output);
CALL `Country_Create`('Peru',@output);
CALL `Country_Create`('Philippines',@output);
CALL `Country_Create`('Pitcairn',@output);
CALL `Country_Create`('Poland',@output);
CALL `Country_Create`('Portugal',@output);
CALL `Country_Create`('Puerto Rico',@output);
CALL `Country_Create`('Qatar',@output);
CALL `Country_Create`('Reunion',@output);
CALL `Country_Create`('Romania',@output);
CALL `Country_Create`('Russian Federation',@output);
CALL `Country_Create`('Rwanda',@output);
CALL `Country_Create`('Saint Helena',@output);
CALL `Country_Create`('Saint Kitts And Nevis',@output);
CALL `Country_Create`('Saint Lucia',@output);
CALL `Country_Create`('Saint Pierre And Miquelon',@output);
CALL `Country_Create`('Saint Vincent And The Grenadines',@output);
CALL `Country_Create`('Samoa',@output);
CALL `Country_Create`('San Marino',@output);
CALL `Country_Create`('Sao Tome And Principe',@output);
CALL `Country_Create`('Saudi Arabia',@output);
CALL `Country_Create`('Senegal',@output);
CALL `Country_Create`('Serbia',@output);
CALL `Country_Create`('Seychelles',@output);
CALL `Country_Create`('Sierra Leone',@output);
CALL `Country_Create`('Singapore',@output);
CALL `Country_Create`('Slovakia',@output);
CALL `Country_Create`('Slovenia',@output);
CALL `Country_Create`('Solomon Islands',@output);
CALL `Country_Create`('Somalia',@output);
CALL `Country_Create`('South Africa',@output);
CALL `Country_Create`('South Georgia And The South Sandwich Islands',@output);
CALL `Country_Create`('Spain',@output);
CALL `Country_Create`('Sri Lanka',@output);
CALL `Country_Create`('Sudan',@output);
CALL `Country_Create`('Suriname',@output);
CALL `Country_Create`('Svalbard And Jan Mayen',@output);
CALL `Country_Create`('Swaziland',@output);
CALL `Country_Create`('Sweden',@output);
CALL `Country_Create`('Switzerland',@output);
CALL `Country_Create`('Syrian Arab Republic',@output);
CALL `Country_Create`('Taiwan, Province Of China',@output);
CALL `Country_Create`('Tajikistan',@output);
CALL `Country_Create`('Tanzania, United Republic Of',@output);
CALL `Country_Create`('Thailand',@output);
CALL `Country_Create`('Timor-leste',@output);
CALL `Country_Create`('Togo',@output);
CALL `Country_Create`('Tokelau',@output);
CALL `Country_Create`('Tonga',@output);
CALL `Country_Create`('Trinidad And Tobago',@output);
CALL `Country_Create`('Tunisia',@output);
CALL `Country_Create`('Turkey',@output);
CALL `Country_Create`('Turkmenistan',@output);
CALL `Country_Create`('Turks And Caicos Islands',@output);
CALL `Country_Create`('Tuvalu',@output);
CALL `Country_Create`('Uganda',@output);
CALL `Country_Create`('Ukraine',@output);
CALL `Country_Create`('United Arab Emirates',@output);
CALL `Country_Create`('United Kingdom',@output);
CALL `Country_Create`('United States',@output);
CALL `Country_Create`('United States Minor Outlying Islands',@output);
CALL `Country_Create`('Uruguay',@output);
CALL `Country_Create`('Uzbekistan',@output);
CALL `Country_Create`('Vanuatu',@output);
CALL `Country_Create`('Venezuela',@output);
CALL `Country_Create`('Viet Nam',@output);
CALL `Country_Create`('Virgin Islands, British',@output);
CALL `Country_Create`('Virgin Islands, U.S.',@output);
CALL `Country_Create`('Wallis And Futuna',@output);
CALL `Country_Create`('Western Sahara',@output);
CALL `Country_Create`('Yemen',@output);
CALL `Country_Create`('Zambia',@output);
CALL `Country_Create`('Zimbabwe',@output);

CALL `ProductLine_Create` ('Lion', 'The Lion is one of the largest, strongest and powerful felines in the world second only in size to the Siberian Tiger. \n\nThey are the largest cats on the African continent and are unique among felines in a number of ways but the biggest difference between Lions and other cats is that they are incredibly sociable animals that live together in family groups known as prides. \n\nLions are also part of the big cat family meaning that both males and females are able to roar. Despite having once roamed across much of Africa and even parts of Europe and Asia, the world''s remaining Lion population now resides in sub-Saharan Africa. However, with Lion numbers thought to have dropped by 30% over the past 20 years these enormous predators are sadly becoming more and more vulnerable in their decreasing natural environment. ', @output);
CALL `ProductLine_Create` ('Zebra', 'The Zebra is a large species of equine that is natively found roaming the grassy plains of sub-Saharan Africa. They are the largest and most distinctive wild horses with bodies that are patterned with white and black stripes, the exact placement of which is unique to each individual. \n\nThere are three different species of Zebra that are found in Africa which are the Common Zebra (also known as the Plains Zebra and the Burchell''s Zebra), the Grevy''s Zebra (also known as the Imperial Zebra) and the Mountain Zebra. They are incredibly sociable animals that can travel vast distances in search of fresh grass and water but are severely threatened throughout much of their natural range due to increasing levels of human activity. \n\nToday, both the Grevy''s Zebra and the Mountain Zebra are considered to be endangered species and although the Common Zebra is more widespread and numerous, there have been sharp population declines in certain areas. ', @output);
CALL `ProductLine_Create` ('Crocodile', 'Crocodiles are one of the planets oldest living creatures, thought to be around 200 million years old which means that crocodiles were around in dinosaur times.\n\nCrocodiles live throughout the watery tropics of Africa, Asia, America and Australia, congregating in freshwater environments in the worlds lakes and rivers. Crocodiles feed on fish, reptiles and mammals, the prey size generally dependent on the size of the crocodile.\n\nLegend has it that if you are being chased by a crocodile, the only chance you have of getting away is by outsmarting the crocodile. Apparently the way to do this is to run away from the crocodile diagonally down a hill! The myth says that crocodiles have a very slow turning circle meaning that if you run diagonally, the crocodile theoretically cant catch you!', @output);
CALL `ProductLine_Create` ('Yak', 'The yak is a herd animal found in the mountainous regions of central Asia. The yak tend to gather in herds from 10 yaks to 100 yaks, most of which are female. There are only a few male yaks per herd.\n\nAlthough there is a large domestic population of yak, there are only a few wild yak remaining . The yak is still used in many parts of central Asia, for pulling heavy farm machines and transporting large loads through the mountain passes.\n\nThe average male yak can grow to about 2meters tall, with the female yak being about 1/3 the size of the male yak. All yak have very long hair to keep them warm.', @output);
CALL `ProductLine_Create` ('Hippopotamus', 'The Hippopotamus is a large semi-aquatic mammal that is found wallowing in the rivers and lakes across sub-Saharan Africa. Despite it''s appearance, the Hippopotamus is actually thought to be most closely related to Whales as the two are thought to have had a common ancestor that existed roughly 54 million years ago. Also known as the Common Hippopotamus, it is one of two Hippo species that are found on the African continent with the other being the solitary and forest-dwelling Pygmy Hippopotamus which is only found in western Africa and is now Critically Endangered. Although the Common Hippopotamus remains abundant and widespread throughout it''s current range, numbers are reportedly declining due to both hunting and habitat loss. ', @output);
CALL `ProductLine_Create` ('Elephant', 'There are numerous subspecies of the Asian elephant, these are the Indian Elephant, Sri Lankan Elephant, Sumatran, Borneo Elephant.\n\nAfrican elephants are larger than Asian elephants and have two subspecies which are the African Bush Elephant and African Forest Elephant.\n\nThe elephant is the only known mammal that, despite having knee joints, cannot jump! This is thought to be primarily due to the elephants sheer size but also because of the way that the elephants legs are built, they are short and stocky to support the elephants phenomenal weight.\n\nElephants are herbivores that spend around 22 hours eating! The elephant searches for green leaves in the tree tops but it is not uncommon for the elephant to tear down the tree to get the leaves.', @output);
CALL `ProductLine_Create` ('Giraffe', 'The Giraffe is a long-necked, hoofed mammal that is natively found grazing in the open woodlands of sub-Saharan Africa. The Giraffe is the tallest living animal on land and despite it''s height is mostly closely related to the much smaller and solitary Okapi, that is found elusively dwelling in the dense tropical forests. There are nine recognised sub-species of Giraffe that are found in differing geographic locations and vary somewhat in the colour and pattern of their spot-like markings. Although the Giraffe would have once been found across sub-Saharan Africa and even in parts of North Africa, today they are extinct from much of their historically vast natural range with only small, isolated populations remaining in a handful of regions in central Africa. Further south however, Giraffe populations are considered to be stable and are even growing in some areas due to an increase in demand for them on private ranches.', @output);
CALL `ProductLine_Create` ('Antelope', 'The antelope is a deer-like mammal found in Africa, Asia and parts of the Americas. There are many different species of antelope including the tiny Royal antelope that stands at the height of a rabbit!\n\nUnlike deer that renew their horns annually, the antelope has strong permanent horns, that antelope mainly use to defend their herd or to fight other antelopes.\n\nAn antelope tends to get to between 8 and 10 years old in the wild although they have been known to live for longer when kept in captivity. Many antelope individuals however, wouldn''t last into old age in the wild as antelope are a key target for many large carnivorous mammals. If the antelope was old then the antelope would naturally be slower at running from danger.', @output);


CALL `Product_Create` ('Asiatic lion','The most striking morphological character, which is always seen in Asiatic lions, and rarely in African lions, is a longitudinal fold of skin running along its belly. Asiatic lions are slightly smaller than African lions. Adult males weigh 160 to 190 kg (350 to 420 lb), while females weigh 110 to 120 kg (240 to 260 lb). The height at the shoulders is about 3.5 ft (110 cm). The record total length of a male Asiatic lion is 2.92 m (115 in) including the tail.\n\nThe fur ranges in colour from ruddy-tawny, heavily speckled with black, to sandy or buffish-grey, sometimes with a silvery sheen in certain lights. Males have only moderate mane growth at the top of the head, so that their ears are always visible. The mane is scanty on the cheeks and throat with where it is only 4 in (10 cm) long.', 1, 15, 1299.99, @output );
CALL `Product_Create` ('Barbary lion','Museum specimens of male Barbary lion were described as having very dark and long-haired manes that extended over the shoulder and to the belly. Head-to-tail length of stuffed males varies from 2.35 to 2.8 m (7 ft 9 in to 9 ft 2 in), and females measure around 2.5 m (8 ft 2 in). A 19th century hunter described a large male allegedly measuring 3.25 m (10.7 ft) including a 75 cm (30 in) long tail. In some historic accounts the weight of wild males was indicated as very heavy and reaching 270 to 300 kilograms (600 to 660 lb). But this range is considered greatly exaggerated. Captive Barbary lions were not known to attain this weight.', 1, 10, 1499.99, @output );
CALL `Product_Create` ('West African lion','Lions from western and central Africa are believed to be smaller than lions from southern Africa. It is also suggested, that they have smaller manes, live in smaller groups, and they may also differ in the shape of their skull. In the Pendjari National Park area, which is within the range of the West African lion, almost all males are maneless or have very weak manes', 1, 15, 999.99, @output );
CALL `Product_Create` ('Masai lion','Neumann first described the Masai lion as being less cobby with longer legs and less curved backs than other lion subspecies. Males have moderate tufts of hair on the knee joint, and their manes are not full but look like combed backwards.\n\nMale East African lions are generally 2.5-3.0 metres (8.2-9.8 feet) long including the tail. Lionesses are generally smaller, at only 2.3-2.6 metres (7.5-8.5 feet). Lions, male or female, have a shoulder height of 0.9-1.10 metres (3.0-3.6 feet).\n\nMale Masai lions are known for a great range of mane types. Mane development is related to age: older males have more extensive manes than younger ones; manes continue to grow up to the age of four to five years, long after lions have become sexually mature. Males living in the highlands above 800 m (2,600 ft) altitude develop heavier manes than lions in the more humid and warmer lowlands of eastern and northern Kenya. They have scanty manes or are even completely maneless.', 1, 6, 1870.00, @output );
CALL `Product_Create` ('Asiatic lion','The most striking morphological character, which is always seen in Asiatic lions, and rarely in African lions, is a longitudinal fold of skin running along its belly. Asiatic lions are slightly smaller than African lions. Adult males weigh 160 to 190 kg (350 to 420 lb), while females weigh 110 to 120 kg (240 to 260 lb). The height at the shoulders is about 3.5 ft (110 cm). The record total length of a male Asiatic lion is 2.92 m (115 in) including the tail.\n\nThe fur ranges in colour from ruddy-tawny, heavily speckled with black, to sandy or buffish-grey, sometimes with a silvery sheen in certain lights. Males have only moderate mane growth at the top of the head, so that their ears are always visible. The mane is scanty on the cheeks and throat with where it is only 4 in (10 cm) long.', 1, 15, 1299.99, @output );

CALL `Product_Create` ('Mountain zebra','Like all extant zebras, it is boldly striped in black and white and no two individuals look exactly alike. The stripes can be either black or dark brown and white. Their stripes cover their whole bodies except for their bellies. The mountain zebra also has a dewlap.\n\nAdult mountain zebras have a head-and-body length of 2.1 to 2.7 m (6 ft 11 in to 8 ft 10 in) and a tail of 40 to 55 cm (16 to 22 in) long. Shoulder height ranges from 1.1 to 1.5 m (3 ft 7 in to 4 ft 11 in). They weigh from 204 to 372 kg (450 to 820 lb). Groves and Bell found that the Cape mountain zebra exhibits sexual dimorphism, with larger females than males, while the Hartmann''s mountain zebra does not. The black stripes of Hartmann''s mountain zebra are thin with much wider white interspaces, while this is the opposite in the Cape mountain zebra.', 2, 12, 1399.99, @output );
CALL `Product_Create` ('Plains zebra','The plains zebra is mid-sized, smaller on average than the other two zebra species, and thick bodied with relatively short legs. There is some variation in size, based on the animals'' condition and subspecies. Adults of both sexes can stand from 1.1 to 1.47 m (3.6 to 4.8 ft) high at the withers (shoulder), are 2 to 2.5 m (6.6 to 8.2 ft) long, not counting a 50 cm (20 in) tail, and weigh 175 to 387 kg (386 to 853 lb). About 14.2hh to 16.0 hh. Males may weigh 10% more than females.', 2, 3, 399.99, @output );
CALL `Product_Create` ('Grevy''s zebra','The Grevy''s zebra is the largest of all wild equines. It is 2.5-3 m (8-9.8 ft) from head to tail with a 38-75 cm (15-30 in) tail, and stands 1.45-1.60 m (4''7"-5''3"; 13 to 16 hands) high at the shoulder. These zebras weigh 350-450 kg (770-990 lb).Grevy''s zebra differs from the other two zebras in its more primitive characteristics. It is particularly mule-like in appearance; the head is large, long, and narrow with elongated nostril openings; the ears are very large, rounded, and conical and the neck is short but thick. The zebra''s muzzle is ash-grey to black in color with the lips having whiskers. The mane is tall and erect; juveniles have a mane that extends to the length of the back and shortens as they reach adulthood', 2, 3, 399.99, @output );

CALL `Product_Create` ('American crocodile','Like all crocodilians, the American crocodile is a quadruped, with four short, stocky legs, a long, powerful tail and a scaly hide with rows of ossified scutes running down its back and tail. Its snout is elongated and includes a strong pair of jaws. Its eyes have nictitating membranes for protection along with lachrymal glands, which produce tears.\n\nThe nostrils, eyes, and ears are situated on the top of its head, so the rest of the body can be concealed underwater for surprise attacks. Camouflage also helps it prey on food. The snout is relatively longer and narrower than that of the American alligator, although broader on average than that of the Orinoco crocodile. American crocodiles are also paler and more grayish than the relatively dark-hued alligator. This crocodile species normally crawls on its belly, but it can also "high walk". Larger specimens can charge up to 10 mph (16 km/h).', 2, 28, 999.99, @output );
CALL `Product_Create` ('Nile crocodile','Nile crocodiles have a dark bronze colouration above, with black spots on the back and a dirty purple on the belly. The flanks, which are yellowish-green in colour, have dark patches arranged in oblique stripes. There is some variation relative to environment; specimens from swift-flowing waters tend to be lighter in colour than those dwelling in lakes or swamps. They have green eyes', 3, 17, 1399.99, @output );
CALL `Product_Create` ('Saltwater crocodile','The saltwater crocodile has a wide snout compared to most crocodiles. However it has a longer muzzle than the mugger crocodile; its length is twice its width at the base.  The saltwater crocodile has fewer armour plates on its neck than other crocodilians. On this species, a pair of ridges runs from the eyes along the centre of the snout. The scales are oval in shape and the scutes are small compared to other species. The adult saltwater crocodile''s broad body contrasts with that of most other lean crocodiles, leading to early unverified assumptions the reptile was an alligator.[18] The head is very large. Skull lengths of more than 75 cm (30 in) have been confirmed for the species and mandibular lengths have been reported of up to 98.3 cm (38.7 in) (female skull lengths of over 50 cm (20 in) are exceptional). The teeth are also long, with the largest teeth (the fourth tooth from the front on the lower jaw) having been measured to 9 cm (3.5 in) in length.', 3, 17, 1499.99, @output );

CALL `Product_Create` ('Wild yak','Yaks are heavily built animals with a bulky frame, sturdy legs, and rounded cloven hooves. They are the only wild bovids of this size with extremely dense, long fur that hangs down lower than the belly. Wild yaks are generally dark, blackish to brown, in colouration. However, domestic yaks can be quite variable in colour, often having patches of rusty brown and cream. In males, the horns sweep out from the sides of the head, and then curve forward; they typically range from 48 to 99 cm (19 to 39 in) in length. The horns of females are smaller, only 27 to 64 cm (11 to 25 in) in length, and have a more upright shape. Both sexes have a short neck with a pronounced hump over the shoulders, although this is larger and more visible in males.\n\n Yaks are highly friendly in nature and can easily be trained. There has been very little documented aggression from yaks towards human beings, although mothers can be extremely protective of their young and will bluff charge if they feel threatened.', 4, 17, 1499.99, @output );


CALL `Customer_Create` ('Smith', 'Bradley', @output);
CALL `Customer_Create` ('Jones', 'Matthew', @output);
CALL `Customer_Create` ('Evans', 'Mark', @output);
CALL `Customer_Create` ('Niles', 'Luke', @output);
CALL `Customer_Create` ('Stout', 'John', @output);
CALL `Customer_Create` ('Chang', 'Stephen', @output);
CALL `Customer_Create` ('Johnson', 'Cyril', @output);
CALL `Customer_Create` ('Burton', 'Archibald', @output);
CALL `Customer_Create` ('Newton', 'Imogen', @output);
CALL `Customer_Create` ('Smith', 'Elizabeth', @output);
CALL `Customer_Create` ('Mirtle', 'Mary', @output);
CALL `Customer_Create` ('Baker', 'Penelope', @output);
CALL `Customer_Create` ('Stafford', 'Mira', @output);
CALL `Customer_Create` ('Young', 'Jennifer', @output);


CALL `StaffMember_Create` ('Pitt', 'Helen', @output);
CALL `StaffMember_Create` ('Norman', 'Harry', @output);
CALL `StaffMember_Create` ('Kirkbride', 'Nancy', @output);
CALL `StaffMember_Create` ('MacDonald', 'Martin', @output);
CALL `StaffMember_Create` ('de Contre', 'Alain', @output);
CALL `StaffMember_Create` ('Brightman', 'Sidney', @output);
CALL `StaffMember_Create` ('Garfield', 'Sally', @output);
CALL `StaffMember_Create` ('Grant', 'Terry', @output);
CALL `StaffMember_Create` ('Underwood', 'Keith', @output);
CALL `StaffMember_Create` ('Williams', 'Fran', @output);
CALL `StaffMember_Create` ('Arden', 'Edith', @output);

CALL `Customer_newCreditCard`('MasterCard', '987654321', 1, @output);
CALL `Customer_newCreditCard`('Visa', '987654322', 1, @output);
CALL `Customer_newCreditCard`('MasterCard', '987654323', 2, @output);
CALL `Customer_newCreditCard`('Visa', '987654324', 2, @output);
CALL `Customer_newCreditCard`('AmericanExpress', '987654325', 3, @output);

CALL `Customer_newAddress`('350 Fifth Avenue', 'New York', '', 230 , 'NY 10118', 1, @output);
